const Colors = {
  MAIN_COLOR: '#3257C4',
  // MAIN_GRADIENT:'#82A5FF',
  BLACK: '#000000',
  WHITE: '#FFFFFF',
  LIGHT_GREY: '#DEDEDE',
  GREY: '#ADADAD',
  DARK_GREY: '#7A7A7A',
  LIGHT_BLUE: '#eef3ff',
  BACKGROUND: '#F5F5F5',
  LINK_COLOR: '#1a73e8',
  // BACKGROUND: '#daecf0',
  LIGHT_BACKGROUND: '#C8D2F7',
  CHARCOAL_GRAY: '#303030',
  SUCCESS_GREEN: '#4CAF50',
  RED_ERROR: '#E11D48',
  CARD_BACKGROUND: '#EDF1FE',
  BUTTON_BACKGROUND: '#4E71D9',
};

export default Colors;
