import { StyleSheet } from 'react-native';
import metrics from '../../constants/metrics';
import Colors from '../../constants/color';

const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    padding: Math.min(metrics.padding(16)),
    backgroundColor: Colors.WHITE,
    minHeight: '100%',
  },
  card: {
    backgroundColor: Colors.WHITE,
    padding: metrics.padding(20),
    flex: 1,
  },
  taskerCard: {
    // flex: 1,
    marginTop: metrics.marginTop(10),
    backgroundColor: Colors.CARD_BACKGROUND,
    padding: metrics.padding(15),
    borderRadius: metrics.borderRadius(10),
    marginVertical: metrics.marginVertical(10),
    elevation: 8,
    shadowColor: Colors.MAIN_COLOR,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.13,
    shadowRadius: 18,
    position: 'relative',
    borderWidth: 1,
    borderColor: Colors.LIGHT_GREY,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: metrics.marginBottom(3),
  },
  title: {
    fontWeight: 'bold',
    fontSize: metrics.fontSize(24),
    color: Colors.CHARCOAL_GRAY,
    marginBottom: metrics.marginBottom(8),
  },
  verifiedRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  verifiedIcon: {
    color: Colors.SUCCESS_GREEN,
    fontWeight: 'medium',
    fontSize: metrics.fontSize(12),
  },
  verifiedText: {
    color: Colors.SUCCESS_GREEN,
    marginLeft: metrics.marginLeft(5),
    fontSize: metrics.fontSize(12),
    fontWeight: '500',
  },
  ratingRow: {
    flexDirection: 'row',
    // marginVertical: metrics.marginVertical(5),
    // marginBottom: 5,
  },
  star: {
    color: Colors.MAIN_COLOR,
    fontSize: metrics.fontSize(15),
  },
  starEmpty: {
    color: Colors.GREY,
    fontSize: metrics.fontSize(15),
  },
  locationRow: {
    flexDirection: 'row',
    // alignItems: 'center',
    gap: metrics.gap(5),
    // flex: 1,

    // marginBottom: metrics.marginBottom(5),
  },
  row: {
    flexDirection: 'column',
    marginTop: metrics.marginTop(3),
  },
  textBold: {
    fontSize: metrics.fontSize(13),
    fontWeight: '600',
    color: Colors.CHARCOAL_GRAY,
    // marginBottom: 10,
    // marginTop: 3,
  },
  textMuted: {
    fontSize: metrics.fontSize(12),
    color: Colors.DARK_GREY,
    textTransform: 'capitalize',
    // marginTop: 3,
    justifyContent: 'center',
    // marginBottom: metrics.marginBottom(5),
  },
  divider: {
    borderBottomWidth: 0.5,
    borderBottomColor: Colors.GREY,
    marginVertical: metrics.marginVertical(10),
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    borderRadius: metrics.borderRadius(20),
    paddingVertical: metrics.paddingVertical(3),
    paddingHorizontal: metrics.paddingHorizontal(4),
    marginTop: metrics.marginTop(5),
    marginRight: metrics.marginRight(1),
    backgroundColor: Colors.LIGHT_GREY,
    alignSelf: 'flex-start',
    // gap: metrics.gap(50),
  },
  chipIcon: {
    color: 'green',
    marginRight: metrics.marginRight(5),
    fontSize: metrics.fontSize(12),
  },
  chipText: {
    fontSize: metrics.fontSize(10),
    color: Colors.LINK_COLOR,
  },
  button: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    paddingVertical: metrics.paddingVertical(10),
    marginTop: metrics.marginTop(20),
    borderRadius: metrics.borderRadius(8),
    backgroundColor: Colors.MAIN_COLOR,
    marginRight: 8,
  },
  appliedButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    paddingVertical: metrics.paddingVertical(10),
    marginTop: metrics.marginTop(20),
    borderRadius: metrics.borderRadius(8),
    backgroundColor: Colors.SUCCESS_GREEN,
    marginRight: 8,
  },
  iconButton: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    backgroundColor: Colors.WHITE,
    paddingVertical: metrics.paddingVertical(10),
    paddingHorizontal: metrics.paddingHorizontal(16),
    borderRadius: metrics.borderRadius(8),
    alignItems: 'center',
    marginTop: metrics.marginTop(20),
    borderWidth: 1,
    borderColor: Colors.MAIN_COLOR,
    flex: 1,
  },
  buttonText: {
    color: Colors.WHITE,
    fontWeight: 'bold',
    fontSize: metrics.fontSize(16),
  },
  saveButtonText: {
    color: Colors.MAIN_COLOR,
    fontWeight: 'bold',
    fontSize: metrics.fontSize(16),
    marginLeft: 8,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: metrics.gap(10),
    marginTop: metrics.marginTop(15),
    // paddingHorizontal: 20,
    paddingBottom: metrics.paddingBottom(20),
  },
  postedTime: {
    color: Colors.LINK_COLOR,
    fontSize: metrics.fontSize(14),
    marginBottom: metrics.marginBottom(12),
  },
  activitySection: {
    marginTop: metrics.marginTop(10),
  },
  activityTitle: {
    fontSize: metrics.fontSize(14),
    fontWeight: '600',
    color: Colors.CHARCOAL_GRAY,
    marginBottom: metrics.marginBottom(5),
  },
  activityRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: metrics.marginBottom(8),
  },
  activityLabel: {
    fontSize: metrics.fontSize(14),
    color: Colors.DARK_GREY,
  },
  activityValue: {
    fontSize: metrics.fontSize(14),
    color: Colors.CHARCOAL_GRAY,
    fontWeight: '500',
  },
  clientSection: {
    marginTop: metrics.marginTop(10),
  },
  clientTitle: {
    fontSize: metrics.fontSize(14),
    fontWeight: '600',
    color: Colors.CHARCOAL_GRAY,
    marginBottom: metrics.marginBottom(12),
  },
  clientInfo: {
    marginBottom: metrics.marginBottom(8),
  },
  clientLocation: {
    fontSize: metrics.fontSize(12),
    color: Colors.DARK_GREY,
    marginTop: metrics.marginTop(4),
  },
  clientStats: {
    marginTop: metrics.marginTop(8),
  },
  clientStatRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: metrics.marginBottom(4),
  },
  clientStatLabel: {
    fontSize: metrics.fontSize(12),
    color: Colors.DARK_GREY,
  },
  clientStatValue: {
    fontSize: metrics.fontSize(12),
    color: Colors.CHARCOAL_GRAY,
    fontWeight: '500',
  },
  iconContainer: {
    flexDirection: 'row',
    gap: metrics.gap(5),
  },
  checkbox: {
    width: 15,
    height: 15,
    borderWidth: 1.5,
    borderColor: Colors.MAIN_COLOR,
    borderRadius: metrics.borderRadius(10),
    marginRight: metrics.marginRight(12),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.WHITE,
  },
  checkboxSelected: {
    width: 10,
    height: 10,
    backgroundColor: Colors.MAIN_COLOR,
    borderRadius: metrics.borderRadius(6),
  },
  appliedBadgeText: {
    textAlign: 'center',
    flex: 1,
    color: Colors.SUCCESS_GREEN,
    fontWeight: '500',
    fontSize: metrics.fontSize(11),
  },
  mainCard: {
    borderRadius: metrics.borderRadius(28),
    padding: metrics.padding(24),
    marginBottom: metrics.marginBottom(24),
    shadowColor: Colors.MAIN_COLOR,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    position: 'relative',
    overflow: 'hidden',
  },
  headerSection: {
    flexDirection: 'row',
    alignItems: 'center',
    // marginBottom: metrics.marginBottom(20),
  },
  userInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  userName: {
    fontSize: metrics.fontSize(24),
    fontWeight: '700',
    color: Colors.WHITE,
    marginBottom: metrics.marginBottom(8),
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  userMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: metrics.gap(16),
  },
});

export default styles;
