import { Dimensions, StyleSheet } from 'react-native';
import metrics from '../../constants/metrics';
import Colors from '../../constants/color';
const { height, width } = Dimensions.get('window');
const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    padding: metrics.padding(16),
    paddingBottom: metrics.paddingBottom(120),
    // backgroundColor: Colors.BACKGROUND,
    minHeight: '100%',
  },
  listContainer: {
    paddingBottom: metrics.padding(25),
    paddingTop: metrics.padding(5),
  },
  filterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingHorizontal: metrics.padding(10),
    borderBottomWidth: 0.5,
    borderBottomColor: Colors.LIGHT_GREY,
    backgroundColor: Colors.BACKGROUND,
    shadowColor: Colors.BLACK,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 1,
    minHeight: metrics.height(56),
  },
  iconBtn: {
    height: metrics.height(40),
    borderRadius: metrics.borderRadius(10),
    backgroundColor: Colors.WHITE,
    paddingHorizontal: metrics.padding(14),
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: metrics.margin(4),
    shadowColor: Colors.BLACK,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
  },
  searchContainer: {
    flex: 1,
    marginHorizontal: metrics.margin(8),
  },
  newRequestBtn: {
    backgroundColor: Colors.BUTTON_BACKGROUND,
    paddingVertical: metrics.padding(10),
    paddingHorizontal: metrics.padding(18),
    borderRadius: metrics.borderRadius(10),
    shadowColor: '#499cab',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 2,
  },
  newRequestText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: metrics.fontSize(15),
    letterSpacing: 0.2,
  },
  emptyContainer: {
    alignItems: 'center',
    marginTop: metrics.marginTop(40),
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    top: metrics.height(105),
    left: metrics.width(10),
    // top: Math.min(height * 0.08, metrics.height(70)),
    // left: Math.min(width * 0.04, metrics.width(60)),
    zIndex: 1000,
    backgroundColor: 'transparent',
    
  },
  detailText: {
    // fontSize: metrics.fontSize(14),
    color: '#555',
    // marginBottom: metrics.margin(4),
  },
  modalContent: {
    backgroundColor: Colors.WHITE,
    borderRadius: Math.min(width * 0.04, metrics.borderRadius(16)),
    padding: Math.min(width * 0.06, metrics.padding(24)),
    minWidth: Math.min(width * 0.55, metrics.width(220)),
    shadowColor: Colors.BLACK,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  modalTitle: {
    fontSize: Math.min(width * 0.045, metrics.fontSize(14)),
    fontWeight: '700',
    marginBottom: Math.min(height * 0.02, metrics.margin(16)),
    color: Colors.BLACK,
  },
  modalOption: {
    paddingVertical: Math.min(height * 0.012, metrics.padding(10)),
    paddingHorizontal: Math.min(width * 0.02, metrics.padding(8)),
    borderRadius: Math.min(width * 0.02, metrics.borderRadius(8)),
    marginBottom: metrics.margin(6),
    textTransform: 'capitalize',
  },
  modalOptionSelected: {
    backgroundColor: '#e3f2fd',
  },
  modalOptionText: {
    fontSize: Math.min(width * 0.04, metrics.fontSize(12)),
    color: '#333',
    textTransform: 'capitalize',
  },
  modalOptionTextSelected: {
    fontSize: Math.min(width * 0.04, metrics.fontSize(12)),
    color: '#1565c0',
    fontWeight: '700',
    textTransform: 'capitalize',
  },
  filterDropdown: {
    position: 'absolute',
    top: Math.min(height * 0.09, metrics.height(100)),
    left: Math.min(width * 0.04, metrics.width(100)),
    right: Math.min(width * 0.04, metrics.width(100)),
    zIndex: 1000,
    backgroundColor: 'transparent',
  },
  dropdownContent: {
    backgroundColor: Colors.WHITE,
    borderRadius: Math.min(width * 0.04, metrics.borderRadius(16)),
    padding: Math.min(width * 0.06, metrics.padding(24)),
    shadowColor: Colors.BLACK,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  dropdownTitle: {
    fontSize: Math.min(width * 0.045, metrics.fontSize(18)),
    fontWeight: '700',
    marginBottom: Math.min(height * 0.02, metrics.margin(16)),
    color: '#222',
  },
  dropdownOption: {
    paddingVertical: Math.min(height * 0.012, metrics.padding(10)),
    paddingHorizontal: Math.min(width * 0.02, metrics.padding(8)),
    borderRadius: Math.min(width * 0.02, metrics.borderRadius(8)),
    marginBottom: metrics.margin(6),
  },
  dropdownOptionSelected: {
    backgroundColor: '#e3f2fd',
  },
  dropdownOptionText: {
    fontSize: Math.min(width * 0.04, metrics.fontSize(16)),
    color: '#333',
  },
  dropdownOptionTextSelected: {
    fontSize: Math.min(width * 0.04, metrics.fontSize(16)),
    color: '#1565c0',
    fontWeight: '700',
  },
});

export default styles;
